# Generated by Django 3.2.24 on 2024-03-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_customer', to='authentication.customer')),
                ('orders', models.ManyToManyField(related_name='favorites_orders', to='orders.Order')),
                ('restaurants', models.ManyToManyField(related_name='favorites_restaurants', to='restaurants.Restaurant')),
            ],
        ),
    ]
